// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: package.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum representing possible package statuses.
type PackageStatus int32

const (
	PackageStatus_PACKAGE_STATUS_UNSPECIFIED   PackageStatus = 0
	PackageStatus_PACKAGE_STATUS_INSTALLED     PackageStatus = 1
	PackageStatus_PACKAGE_STATUS_NOT_INSTALLED PackageStatus = 2
	PackageStatus_PACKAGE_STATUS_UPDATABLE     PackageStatus = 3
)

// Enum value maps for PackageStatus.
var (
	PackageStatus_name = map[int32]string{
		0: "PACKAGE_STATUS_UNSPECIFIED",
		1: "PACKAGE_STATUS_INSTALLED",
		2: "PACKAGE_STATUS_NOT_INSTALLED",
		3: "PACKAGE_STATUS_UPDATABLE",
	}
	PackageStatus_value = map[string]int32{
		"PACKAGE_STATUS_UNSPECIFIED":   0,
		"PACKAGE_STATUS_INSTALLED":     1,
		"PACKAGE_STATUS_NOT_INSTALLED": 2,
		"PACKAGE_STATUS_UPDATABLE":     3,
	}
)

func (x PackageStatus) Enum() *PackageStatus {
	p := new(PackageStatus)
	*p = x
	return p
}

func (x PackageStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PackageStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_package_proto_enumTypes[0].Descriptor()
}

func (PackageStatus) Type() protoreflect.EnumType {
	return &file_package_proto_enumTypes[0]
}

func (x PackageStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PackageStatus.Descriptor instead.
func (PackageStatus) EnumDescriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{0}
}

type ListPackageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPackageRequest) Reset() {
	*x = ListPackageRequest{}
	mi := &file_package_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPackageRequest) ProtoMessage() {}

func (x *ListPackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPackageRequest.ProtoReflect.Descriptor instead.
func (*ListPackageRequest) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{0}
}

type ListPackageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of available packages.
	Packages      []*GetPackageResponse `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPackageResponse) Reset() {
	*x = ListPackageResponse{}
	mi := &file_package_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPackageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPackageResponse) ProtoMessage() {}

func (x *ListPackageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPackageResponse.ProtoReflect.Descriptor instead.
func (*ListPackageResponse) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{1}
}

func (x *ListPackageResponse) GetPackages() []*GetPackageResponse {
	if x != nil {
		return x.Packages
	}
	return nil
}

type GetPackageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier of the package.
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPackageRequest) Reset() {
	*x = GetPackageRequest{}
	mi := &file_package_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackageRequest) ProtoMessage() {}

func (x *GetPackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPackageRequest.ProtoReflect.Descriptor instead.
func (*GetPackageRequest) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{2}
}

func (x *GetPackageRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetPackageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier of the package.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Name of the package.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Description of the package.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Installation status of the package.
	Status PackageStatus `protobuf:"varint,4,opt,name=Status,proto3,enum=supervisor.PackageStatus" json:"Status,omitempty"`
	// Version of the package.
	Version       string `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPackageResponse) Reset() {
	*x = GetPackageResponse{}
	mi := &file_package_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPackageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackageResponse) ProtoMessage() {}

func (x *GetPackageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPackageResponse.ProtoReflect.Descriptor instead.
func (*GetPackageResponse) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{3}
}

func (x *GetPackageResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetPackageResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetPackageResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetPackageResponse) GetStatus() PackageStatus {
	if x != nil {
		return x.Status
	}
	return PackageStatus_PACKAGE_STATUS_UNSPECIFIED
}

func (x *GetPackageResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type InstallPackageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier of the package.
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallPackageRequest) Reset() {
	*x = InstallPackageRequest{}
	mi := &file_package_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallPackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallPackageRequest) ProtoMessage() {}

func (x *InstallPackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallPackageRequest.ProtoReflect.Descriptor instead.
func (*InstallPackageRequest) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{4}
}

func (x *InstallPackageRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type InstallPackageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallPackageResponse) Reset() {
	*x = InstallPackageResponse{}
	mi := &file_package_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallPackageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallPackageResponse) ProtoMessage() {}

func (x *InstallPackageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallPackageResponse.ProtoReflect.Descriptor instead.
func (*InstallPackageResponse) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{5}
}

func (x *InstallPackageResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RemovePackageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier of the package.
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePackageRequest) Reset() {
	*x = RemovePackageRequest{}
	mi := &file_package_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePackageRequest) ProtoMessage() {}

func (x *RemovePackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePackageRequest.ProtoReflect.Descriptor instead.
func (*RemovePackageRequest) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{6}
}

func (x *RemovePackageRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RemovePackageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePackageResponse) Reset() {
	*x = RemovePackageResponse{}
	mi := &file_package_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePackageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePackageResponse) ProtoMessage() {}

func (x *RemovePackageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePackageResponse.ProtoReflect.Descriptor instead.
func (*RemovePackageResponse) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{7}
}

func (x *RemovePackageResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_package_proto protoreflect.FileDescriptor

const file_package_proto_rawDesc = "" +
	"\n" +
	"\rpackage.proto\x12\n" +
	"supervisor\"\x14\n" +
	"\x12ListPackageRequest\"Q\n" +
	"\x13ListPackageResponse\x12:\n" +
	"\bpackages\x18\x01 \x03(\v2\x1e.supervisor.GetPackageResponseR\bpackages\"#\n" +
	"\x11GetPackageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xa7\x01\n" +
	"\x12GetPackageResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x121\n" +
	"\x06Status\x18\x04 \x01(\x0e2\x19.supervisor.PackageStatusR\x06Status\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\"'\n" +
	"\x15InstallPackageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"0\n" +
	"\x16InstallPackageResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"&\n" +
	"\x14RemovePackageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"/\n" +
	"\x15RemovePackageResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status*\x8d\x01\n" +
	"\rPackageStatus\x12\x1e\n" +
	"\x1aPACKAGE_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18PACKAGE_STATUS_INSTALLED\x10\x01\x12 \n" +
	"\x1cPACKAGE_STATUS_NOT_INSTALLED\x10\x02\x12\x1c\n" +
	"\x18PACKAGE_STATUS_UPDATABLE\x10\x032\xc8\x02\n" +
	"\x0ePackageService\x12I\n" +
	"\x04List\x12\x1e.supervisor.ListPackageRequest\x1a\x1f.supervisor.ListPackageResponse\"\x00\x12F\n" +
	"\x03Get\x12\x1d.supervisor.GetPackageRequest\x1a\x1e.supervisor.GetPackageResponse\"\x00\x12R\n" +
	"\aInstall\x12!.supervisor.InstallPackageRequest\x1a\".supervisor.InstallPackageResponse\"\x00\x12O\n" +
	"\x06Remove\x12 .supervisor.RemovePackageRequest\x1a!.supervisor.RemovePackageResponse\"\x00B\x10Z\x0esupervisor/apib\x06proto3"

var (
	file_package_proto_rawDescOnce sync.Once
	file_package_proto_rawDescData []byte
)

func file_package_proto_rawDescGZIP() []byte {
	file_package_proto_rawDescOnce.Do(func() {
		file_package_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_package_proto_rawDesc), len(file_package_proto_rawDesc)))
	})
	return file_package_proto_rawDescData
}

var file_package_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_package_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_package_proto_goTypes = []any{
	(PackageStatus)(0),             // 0: supervisor.PackageStatus
	(*ListPackageRequest)(nil),     // 1: supervisor.ListPackageRequest
	(*ListPackageResponse)(nil),    // 2: supervisor.ListPackageResponse
	(*GetPackageRequest)(nil),      // 3: supervisor.GetPackageRequest
	(*GetPackageResponse)(nil),     // 4: supervisor.GetPackageResponse
	(*InstallPackageRequest)(nil),  // 5: supervisor.InstallPackageRequest
	(*InstallPackageResponse)(nil), // 6: supervisor.InstallPackageResponse
	(*RemovePackageRequest)(nil),   // 7: supervisor.RemovePackageRequest
	(*RemovePackageResponse)(nil),  // 8: supervisor.RemovePackageResponse
}
var file_package_proto_depIdxs = []int32{
	4, // 0: supervisor.ListPackageResponse.packages:type_name -> supervisor.GetPackageResponse
	0, // 1: supervisor.GetPackageResponse.Status:type_name -> supervisor.PackageStatus
	1, // 2: supervisor.PackageService.List:input_type -> supervisor.ListPackageRequest
	3, // 3: supervisor.PackageService.Get:input_type -> supervisor.GetPackageRequest
	5, // 4: supervisor.PackageService.Install:input_type -> supervisor.InstallPackageRequest
	7, // 5: supervisor.PackageService.Remove:input_type -> supervisor.RemovePackageRequest
	2, // 6: supervisor.PackageService.List:output_type -> supervisor.ListPackageResponse
	4, // 7: supervisor.PackageService.Get:output_type -> supervisor.GetPackageResponse
	6, // 8: supervisor.PackageService.Install:output_type -> supervisor.InstallPackageResponse
	8, // 9: supervisor.PackageService.Remove:output_type -> supervisor.RemovePackageResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_package_proto_init() }
func file_package_proto_init() {
	if File_package_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_package_proto_rawDesc), len(file_package_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_package_proto_goTypes,
		DependencyIndexes: file_package_proto_depIdxs,
		EnumInfos:         file_package_proto_enumTypes,
		MessageInfos:      file_package_proto_msgTypes,
	}.Build()
	File_package_proto = out.File
	file_package_proto_goTypes = nil
	file_package_proto_depIdxs = nil
}
