// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: port.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TunnelVisibility int32

const (
	TunnelVisibility_none    TunnelVisibility = 0
	TunnelVisibility_host    TunnelVisibility = 1
	TunnelVisibility_network TunnelVisibility = 2
)

// Enum value maps for TunnelVisibility.
var (
	TunnelVisibility_name = map[int32]string{
		0: "none",
		1: "host",
		2: "network",
	}
	TunnelVisibility_value = map[string]int32{
		"none":    0,
		"host":    1,
		"network": 2,
	}
)

func (x TunnelVisibility) Enum() *TunnelVisibility {
	p := new(TunnelVisibility)
	*p = x
	return p
}

func (x TunnelVisibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TunnelVisibility) Descriptor() protoreflect.EnumDescriptor {
	return file_port_proto_enumTypes[0].Descriptor()
}

func (TunnelVisibility) Type() protoreflect.EnumType {
	return &file_port_proto_enumTypes[0]
}

func (x TunnelVisibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TunnelVisibility.Descriptor instead.
func (TunnelVisibility) EnumDescriptor() ([]byte, []int) {
	return file_port_proto_rawDescGZIP(), []int{0}
}

type TunnelPortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          uint32                 `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	TargetPort    uint32                 `protobuf:"varint,2,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	Visibility    TunnelVisibility       `protobuf:"varint,3,opt,name=visibility,proto3,enum=supervisor.TunnelVisibility" json:"visibility,omitempty"`
	ClientId      string                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelPortRequest) Reset() {
	*x = TunnelPortRequest{}
	mi := &file_port_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelPortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelPortRequest) ProtoMessage() {}

func (x *TunnelPortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_port_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelPortRequest.ProtoReflect.Descriptor instead.
func (*TunnelPortRequest) Descriptor() ([]byte, []int) {
	return file_port_proto_rawDescGZIP(), []int{0}
}

func (x *TunnelPortRequest) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *TunnelPortRequest) GetTargetPort() uint32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

func (x *TunnelPortRequest) GetVisibility() TunnelVisibility {
	if x != nil {
		return x.Visibility
	}
	return TunnelVisibility_none
}

func (x *TunnelPortRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type TunnelPortResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelPortResponse) Reset() {
	*x = TunnelPortResponse{}
	mi := &file_port_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelPortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelPortResponse) ProtoMessage() {}

func (x *TunnelPortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_port_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelPortResponse.ProtoReflect.Descriptor instead.
func (*TunnelPortResponse) Descriptor() ([]byte, []int) {
	return file_port_proto_rawDescGZIP(), []int{1}
}

type CloseTunnelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          uint32                 `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseTunnelRequest) Reset() {
	*x = CloseTunnelRequest{}
	mi := &file_port_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseTunnelRequest) ProtoMessage() {}

func (x *CloseTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_port_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseTunnelRequest.ProtoReflect.Descriptor instead.
func (*CloseTunnelRequest) Descriptor() ([]byte, []int) {
	return file_port_proto_rawDescGZIP(), []int{2}
}

func (x *CloseTunnelRequest) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type CloseTunnelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseTunnelResponse) Reset() {
	*x = CloseTunnelResponse{}
	mi := &file_port_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseTunnelResponse) ProtoMessage() {}

func (x *CloseTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_port_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseTunnelResponse.ProtoReflect.Descriptor instead.
func (*CloseTunnelResponse) Descriptor() ([]byte, []int) {
	return file_port_proto_rawDescGZIP(), []int{3}
}

type EstablishTunnelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Output:
	//
	//	*EstablishTunnelRequest_Desc
	//	*EstablishTunnelRequest_Data
	Output        isEstablishTunnelRequest_Output `protobuf_oneof:"output"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstablishTunnelRequest) Reset() {
	*x = EstablishTunnelRequest{}
	mi := &file_port_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstablishTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstablishTunnelRequest) ProtoMessage() {}

func (x *EstablishTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_port_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstablishTunnelRequest.ProtoReflect.Descriptor instead.
func (*EstablishTunnelRequest) Descriptor() ([]byte, []int) {
	return file_port_proto_rawDescGZIP(), []int{4}
}

func (x *EstablishTunnelRequest) GetOutput() isEstablishTunnelRequest_Output {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *EstablishTunnelRequest) GetDesc() *TunnelPortRequest {
	if x != nil {
		if x, ok := x.Output.(*EstablishTunnelRequest_Desc); ok {
			return x.Desc
		}
	}
	return nil
}

func (x *EstablishTunnelRequest) GetData() []byte {
	if x != nil {
		if x, ok := x.Output.(*EstablishTunnelRequest_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isEstablishTunnelRequest_Output interface {
	isEstablishTunnelRequest_Output()
}

type EstablishTunnelRequest_Desc struct {
	Desc *TunnelPortRequest `protobuf:"bytes,1,opt,name=desc,proto3,oneof"`
}

type EstablishTunnelRequest_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*EstablishTunnelRequest_Desc) isEstablishTunnelRequest_Output() {}

func (*EstablishTunnelRequest_Data) isEstablishTunnelRequest_Output() {}

type EstablishTunnelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstablishTunnelResponse) Reset() {
	*x = EstablishTunnelResponse{}
	mi := &file_port_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstablishTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstablishTunnelResponse) ProtoMessage() {}

func (x *EstablishTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_port_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstablishTunnelResponse.ProtoReflect.Descriptor instead.
func (*EstablishTunnelResponse) Descriptor() ([]byte, []int) {
	return file_port_proto_rawDescGZIP(), []int{5}
}

func (x *EstablishTunnelResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type AutoTunnelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutoTunnelRequest) Reset() {
	*x = AutoTunnelRequest{}
	mi := &file_port_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoTunnelRequest) ProtoMessage() {}

func (x *AutoTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_port_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoTunnelRequest.ProtoReflect.Descriptor instead.
func (*AutoTunnelRequest) Descriptor() ([]byte, []int) {
	return file_port_proto_rawDescGZIP(), []int{6}
}

func (x *AutoTunnelRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type AutoTunnelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutoTunnelResponse) Reset() {
	*x = AutoTunnelResponse{}
	mi := &file_port_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoTunnelResponse) ProtoMessage() {}

func (x *AutoTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_port_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoTunnelResponse.ProtoReflect.Descriptor instead.
func (*AutoTunnelResponse) Descriptor() ([]byte, []int) {
	return file_port_proto_rawDescGZIP(), []int{7}
}

type RetryAutoExposeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          uint32                 `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryAutoExposeRequest) Reset() {
	*x = RetryAutoExposeRequest{}
	mi := &file_port_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryAutoExposeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryAutoExposeRequest) ProtoMessage() {}

func (x *RetryAutoExposeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_port_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryAutoExposeRequest.ProtoReflect.Descriptor instead.
func (*RetryAutoExposeRequest) Descriptor() ([]byte, []int) {
	return file_port_proto_rawDescGZIP(), []int{8}
}

func (x *RetryAutoExposeRequest) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type RetryAutoExposeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryAutoExposeResponse) Reset() {
	*x = RetryAutoExposeResponse{}
	mi := &file_port_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryAutoExposeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryAutoExposeResponse) ProtoMessage() {}

func (x *RetryAutoExposeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_port_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryAutoExposeResponse.ProtoReflect.Descriptor instead.
func (*RetryAutoExposeResponse) Descriptor() ([]byte, []int) {
	return file_port_proto_rawDescGZIP(), []int{9}
}

var File_port_proto protoreflect.FileDescriptor

const file_port_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"port.proto\x12\n" +
	"supervisor\"\xa3\x01\n" +
	"\x11TunnelPortRequest\x12\x12\n" +
	"\x04port\x18\x01 \x01(\rR\x04port\x12\x1f\n" +
	"\vtarget_port\x18\x02 \x01(\rR\n" +
	"targetPort\x12<\n" +
	"\n" +
	"visibility\x18\x03 \x01(\x0e2\x1c.supervisor.TunnelVisibilityR\n" +
	"visibility\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId\"\x14\n" +
	"\x12TunnelPortResponse\"(\n" +
	"\x12CloseTunnelRequest\x12\x12\n" +
	"\x04port\x18\x01 \x01(\rR\x04port\"\x15\n" +
	"\x13CloseTunnelResponse\"m\n" +
	"\x16EstablishTunnelRequest\x123\n" +
	"\x04desc\x18\x01 \x01(\v2\x1d.supervisor.TunnelPortRequestH\x00R\x04desc\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\b\n" +
	"\x06output\"-\n" +
	"\x17EstablishTunnelResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"-\n" +
	"\x11AutoTunnelRequest\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\"\x14\n" +
	"\x12AutoTunnelResponse\",\n" +
	"\x16RetryAutoExposeRequest\x12\x12\n" +
	"\x04port\x18\x01 \x01(\rR\x04port\"\x19\n" +
	"\x17RetryAutoExposeResponse*3\n" +
	"\x10TunnelVisibility\x12\b\n" +
	"\x04none\x10\x00\x12\b\n" +
	"\x04host\x10\x01\x12\v\n" +
	"\anetwork\x10\x022\xb7\x03\n" +
	"\vPortService\x12I\n" +
	"\x06Tunnel\x12\x1d.supervisor.TunnelPortRequest\x1a\x1e.supervisor.TunnelPortResponse\"\x00\x12P\n" +
	"\vCloseTunnel\x12\x1e.supervisor.CloseTunnelRequest\x1a\x1f.supervisor.CloseTunnelResponse\"\x00\x12^\n" +
	"\x0fEstablishTunnel\x12\".supervisor.EstablishTunnelRequest\x1a#.supervisor.EstablishTunnelResponse(\x010\x01\x12M\n" +
	"\n" +
	"AutoTunnel\x12\x1d.supervisor.AutoTunnelRequest\x1a\x1e.supervisor.AutoTunnelResponse\"\x00\x12\\\n" +
	"\x0fRetryAutoExpose\x12\".supervisor.RetryAutoExposeRequest\x1a#.supervisor.RetryAutoExposeResponse\"\x00B\x10Z\x0esupervisor/apib\x06proto3"

var (
	file_port_proto_rawDescOnce sync.Once
	file_port_proto_rawDescData []byte
)

func file_port_proto_rawDescGZIP() []byte {
	file_port_proto_rawDescOnce.Do(func() {
		file_port_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_port_proto_rawDesc), len(file_port_proto_rawDesc)))
	})
	return file_port_proto_rawDescData
}

var file_port_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_port_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_port_proto_goTypes = []any{
	(TunnelVisibility)(0),           // 0: supervisor.TunnelVisibility
	(*TunnelPortRequest)(nil),       // 1: supervisor.TunnelPortRequest
	(*TunnelPortResponse)(nil),      // 2: supervisor.TunnelPortResponse
	(*CloseTunnelRequest)(nil),      // 3: supervisor.CloseTunnelRequest
	(*CloseTunnelResponse)(nil),     // 4: supervisor.CloseTunnelResponse
	(*EstablishTunnelRequest)(nil),  // 5: supervisor.EstablishTunnelRequest
	(*EstablishTunnelResponse)(nil), // 6: supervisor.EstablishTunnelResponse
	(*AutoTunnelRequest)(nil),       // 7: supervisor.AutoTunnelRequest
	(*AutoTunnelResponse)(nil),      // 8: supervisor.AutoTunnelResponse
	(*RetryAutoExposeRequest)(nil),  // 9: supervisor.RetryAutoExposeRequest
	(*RetryAutoExposeResponse)(nil), // 10: supervisor.RetryAutoExposeResponse
}
var file_port_proto_depIdxs = []int32{
	0,  // 0: supervisor.TunnelPortRequest.visibility:type_name -> supervisor.TunnelVisibility
	1,  // 1: supervisor.EstablishTunnelRequest.desc:type_name -> supervisor.TunnelPortRequest
	1,  // 2: supervisor.PortService.Tunnel:input_type -> supervisor.TunnelPortRequest
	3,  // 3: supervisor.PortService.CloseTunnel:input_type -> supervisor.CloseTunnelRequest
	5,  // 4: supervisor.PortService.EstablishTunnel:input_type -> supervisor.EstablishTunnelRequest
	7,  // 5: supervisor.PortService.AutoTunnel:input_type -> supervisor.AutoTunnelRequest
	9,  // 6: supervisor.PortService.RetryAutoExpose:input_type -> supervisor.RetryAutoExposeRequest
	2,  // 7: supervisor.PortService.Tunnel:output_type -> supervisor.TunnelPortResponse
	4,  // 8: supervisor.PortService.CloseTunnel:output_type -> supervisor.CloseTunnelResponse
	6,  // 9: supervisor.PortService.EstablishTunnel:output_type -> supervisor.EstablishTunnelResponse
	8,  // 10: supervisor.PortService.AutoTunnel:output_type -> supervisor.AutoTunnelResponse
	10, // 11: supervisor.PortService.RetryAutoExpose:output_type -> supervisor.RetryAutoExposeResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_port_proto_init() }
func file_port_proto_init() {
	if File_port_proto != nil {
		return
	}
	file_port_proto_msgTypes[4].OneofWrappers = []any{
		(*EstablishTunnelRequest_Desc)(nil),
		(*EstablishTunnelRequest_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_port_proto_rawDesc), len(file_port_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_port_proto_goTypes,
		DependencyIndexes: file_port_proto_depIdxs,
		EnumInfos:         file_port_proto_enumTypes,
		MessageInfos:      file_port_proto_msgTypes,
	}.Build()
	File_port_proto = out.File
	file_port_proto_goTypes = nil
	file_port_proto_depIdxs = nil
}
