// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: system.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourceStatusSeverity int32

const (
	ResourceStatusSeverity_normal  ResourceStatusSeverity = 0
	ResourceStatusSeverity_warning ResourceStatusSeverity = 1
	ResourceStatusSeverity_danger  ResourceStatusSeverity = 2
)

// Enum value maps for ResourceStatusSeverity.
var (
	ResourceStatusSeverity_name = map[int32]string{
		0: "normal",
		1: "warning",
		2: "danger",
	}
	ResourceStatusSeverity_value = map[string]int32{
		"normal":  0,
		"warning": 1,
		"danger":  2,
	}
)

func (x ResourceStatusSeverity) Enum() *ResourceStatusSeverity {
	p := new(ResourceStatusSeverity)
	*p = x
	return p
}

func (x ResourceStatusSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceStatusSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_system_proto_enumTypes[0].Descriptor()
}

func (ResourceStatusSeverity) Type() protoreflect.EnumType {
	return &file_system_proto_enumTypes[0]
}

func (x ResourceStatusSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceStatusSeverity.Descriptor instead.
func (ResourceStatusSeverity) EnumDescriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{0}
}

type WorkspaceInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceInfoRequest) Reset() {
	*x = WorkspaceInfoRequest{}
	mi := &file_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceInfoRequest) ProtoMessage() {}

func (x *WorkspaceInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceInfoRequest.ProtoReflect.Descriptor instead.
func (*WorkspaceInfoRequest) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{0}
}

type WorkspaceInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// workspace_id is the instance ID of this workspace.
	WorkspaceId int64 `protobuf:"varint,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	// checkout_location is the path where we initialized the workspace content
	CheckoutLocation string `protobuf:"bytes,2,opt,name=checkout_location,json=checkoutLocation,proto3" json:"checkout_location,omitempty"`
	// user_home is the path to the user's home.
	UserHome string `protobuf:"bytes,3,opt,name=user_home,json=userHome,proto3" json:"user_home,omitempty"`
	// workspace_cluster_host provides the cluster host under which this workspace is served
	ClusterHost string `protobuf:"bytes,4,opt,name=cluster_host,json=clusterHost,proto3" json:"cluster_host,omitempty"`
	// workspace_url is an URL for which the workspace is accessed.
	WorkspaceUrl string `protobuf:"bytes,5,opt,name=workspace_url,json=workspaceUrl,proto3" json:"workspace_url,omitempty"`
	// ide_alias is an alias of IDE to be run. Possible values: "code", "code-latest", "theia"
	IdeAlias string `protobuf:"bytes,6,opt,name=ide_alias,json=ideAlias,proto3" json:"ide_alias,omitempty"`
	// ide_port is the port on which the IDE is to be run
	IdePort uint32 `protobuf:"varint,7,opt,name=ide_port,json=idePort,proto3" json:"ide_port,omitempty"`
	// owner_id is user id who owns the workspace
	OwnerId       int64 `protobuf:"varint,8,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceInfoResponse) Reset() {
	*x = WorkspaceInfoResponse{}
	mi := &file_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceInfoResponse) ProtoMessage() {}

func (x *WorkspaceInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceInfoResponse.ProtoReflect.Descriptor instead.
func (*WorkspaceInfoResponse) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{1}
}

func (x *WorkspaceInfoResponse) GetWorkspaceId() int64 {
	if x != nil {
		return x.WorkspaceId
	}
	return 0
}

func (x *WorkspaceInfoResponse) GetCheckoutLocation() string {
	if x != nil {
		return x.CheckoutLocation
	}
	return ""
}

func (x *WorkspaceInfoResponse) GetUserHome() string {
	if x != nil {
		return x.UserHome
	}
	return ""
}

func (x *WorkspaceInfoResponse) GetClusterHost() string {
	if x != nil {
		return x.ClusterHost
	}
	return ""
}

func (x *WorkspaceInfoResponse) GetWorkspaceUrl() string {
	if x != nil {
		return x.WorkspaceUrl
	}
	return ""
}

func (x *WorkspaceInfoResponse) GetIdeAlias() string {
	if x != nil {
		return x.IdeAlias
	}
	return ""
}

func (x *WorkspaceInfoResponse) GetIdePort() uint32 {
	if x != nil {
		return x.IdePort
	}
	return 0
}

func (x *WorkspaceInfoResponse) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

type ResourcesStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourcesStatusRequest) Reset() {
	*x = ResourcesStatusRequest{}
	mi := &file_system_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourcesStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourcesStatusRequest) ProtoMessage() {}

func (x *ResourcesStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourcesStatusRequest.ProtoReflect.Descriptor instead.
func (*ResourcesStatusRequest) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{2}
}

type ResourcesStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the flavor
	Flavor string `protobuf:"bytes,1,opt,name=flavor,proto3" json:"flavor,omitempty"`
	// Used memory and limit in bytes
	Memory *ResourceStatus `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"`
	// Used CPU and limit in millicores.
	Cpu *ResourceStatus `protobuf:"bytes,3,opt,name=cpu,proto3" json:"cpu,omitempty"`
	// Used Disk and limit in bytes
	Disk          *ResourceStatus `protobuf:"bytes,4,opt,name=disk,proto3" json:"disk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourcesStatusResponse) Reset() {
	*x = ResourcesStatusResponse{}
	mi := &file_system_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourcesStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourcesStatusResponse) ProtoMessage() {}

func (x *ResourcesStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourcesStatusResponse.ProtoReflect.Descriptor instead.
func (*ResourcesStatusResponse) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{3}
}

func (x *ResourcesStatusResponse) GetFlavor() string {
	if x != nil {
		return x.Flavor
	}
	return ""
}

func (x *ResourcesStatusResponse) GetMemory() *ResourceStatus {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *ResourcesStatusResponse) GetCpu() *ResourceStatus {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *ResourcesStatusResponse) GetDisk() *ResourceStatus {
	if x != nil {
		return x.Disk
	}
	return nil
}

type ResourceStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Used          int64                  `protobuf:"varint,1,opt,name=used,proto3" json:"used,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Severity      ResourceStatusSeverity `protobuf:"varint,3,opt,name=severity,proto3,enum=supervisor.ResourceStatusSeverity" json:"severity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceStatus) Reset() {
	*x = ResourceStatus{}
	mi := &file_system_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceStatus) ProtoMessage() {}

func (x *ResourceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceStatus.ProtoReflect.Descriptor instead.
func (*ResourceStatus) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{4}
}

func (x *ResourceStatus) GetUsed() int64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *ResourceStatus) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ResourceStatus) GetSeverity() ResourceStatusSeverity {
	if x != nil {
		return x.Severity
	}
	return ResourceStatusSeverity_normal
}

var File_system_proto protoreflect.FileDescriptor

const file_system_proto_rawDesc = "" +
	"\n" +
	"\fsystem.proto\x12\n" +
	"supervisor\"\x16\n" +
	"\x14WorkspaceInfoRequest\"\x9f\x02\n" +
	"\x15WorkspaceInfoResponse\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\x03R\vworkspaceId\x12+\n" +
	"\x11checkout_location\x18\x02 \x01(\tR\x10checkoutLocation\x12\x1b\n" +
	"\tuser_home\x18\x03 \x01(\tR\buserHome\x12!\n" +
	"\fcluster_host\x18\x04 \x01(\tR\vclusterHost\x12#\n" +
	"\rworkspace_url\x18\x05 \x01(\tR\fworkspaceUrl\x12\x1b\n" +
	"\tide_alias\x18\x06 \x01(\tR\bideAlias\x12\x19\n" +
	"\bide_port\x18\a \x01(\rR\aidePort\x12\x19\n" +
	"\bowner_id\x18\b \x01(\x03R\aownerId\"\x18\n" +
	"\x16ResourcesStatusRequest\"\xc3\x01\n" +
	"\x17ResourcesStatusResponse\x12\x16\n" +
	"\x06flavor\x18\x01 \x01(\tR\x06flavor\x122\n" +
	"\x06memory\x18\x02 \x01(\v2\x1a.supervisor.ResourceStatusR\x06memory\x12,\n" +
	"\x03cpu\x18\x03 \x01(\v2\x1a.supervisor.ResourceStatusR\x03cpu\x12.\n" +
	"\x04disk\x18\x04 \x01(\v2\x1a.supervisor.ResourceStatusR\x04disk\"z\n" +
	"\x0eResourceStatus\x12\x12\n" +
	"\x04used\x18\x01 \x01(\x03R\x04used\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12>\n" +
	"\bseverity\x18\x03 \x01(\x0e2\".supervisor.ResourceStatusSeverityR\bseverity*=\n" +
	"\x16ResourceStatusSeverity\x12\n" +
	"\n" +
	"\x06normal\x10\x00\x12\v\n" +
	"\awarning\x10\x01\x12\n" +
	"\n" +
	"\x06danger\x10\x022\xc5\x01\n" +
	"\rSystemService\x12V\n" +
	"\rWorkspaceInfo\x12 .supervisor.WorkspaceInfoRequest\x1a!.supervisor.WorkspaceInfoResponse\"\x00\x12\\\n" +
	"\x0fResourcesStatus\x12\".supervisor.ResourcesStatusRequest\x1a#.supervisor.ResourcesStatusResponse\"\x00B\x10Z\x0esupervisor/apib\x06proto3"

var (
	file_system_proto_rawDescOnce sync.Once
	file_system_proto_rawDescData []byte
)

func file_system_proto_rawDescGZIP() []byte {
	file_system_proto_rawDescOnce.Do(func() {
		file_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_system_proto_rawDesc), len(file_system_proto_rawDesc)))
	})
	return file_system_proto_rawDescData
}

var file_system_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_system_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_system_proto_goTypes = []any{
	(ResourceStatusSeverity)(0),     // 0: supervisor.ResourceStatusSeverity
	(*WorkspaceInfoRequest)(nil),    // 1: supervisor.WorkspaceInfoRequest
	(*WorkspaceInfoResponse)(nil),   // 2: supervisor.WorkspaceInfoResponse
	(*ResourcesStatusRequest)(nil),  // 3: supervisor.ResourcesStatusRequest
	(*ResourcesStatusResponse)(nil), // 4: supervisor.ResourcesStatusResponse
	(*ResourceStatus)(nil),          // 5: supervisor.ResourceStatus
}
var file_system_proto_depIdxs = []int32{
	5, // 0: supervisor.ResourcesStatusResponse.memory:type_name -> supervisor.ResourceStatus
	5, // 1: supervisor.ResourcesStatusResponse.cpu:type_name -> supervisor.ResourceStatus
	5, // 2: supervisor.ResourcesStatusResponse.disk:type_name -> supervisor.ResourceStatus
	0, // 3: supervisor.ResourceStatus.severity:type_name -> supervisor.ResourceStatusSeverity
	1, // 4: supervisor.SystemService.WorkspaceInfo:input_type -> supervisor.WorkspaceInfoRequest
	3, // 5: supervisor.SystemService.ResourcesStatus:input_type -> supervisor.ResourcesStatusRequest
	2, // 6: supervisor.SystemService.WorkspaceInfo:output_type -> supervisor.WorkspaceInfoResponse
	4, // 7: supervisor.SystemService.ResourcesStatus:output_type -> supervisor.ResourcesStatusResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_system_proto_init() }
func file_system_proto_init() {
	if File_system_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_system_proto_rawDesc), len(file_system_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_system_proto_goTypes,
		DependencyIndexes: file_system_proto_depIdxs,
		EnumInfos:         file_system_proto_enumTypes,
		MessageInfos:      file_system_proto_msgTypes,
	}.Build()
	File_system_proto = out.File
	file_system_proto_goTypes = nil
	file_system_proto_depIdxs = nil
}
