// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: terminal.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TerminalTitleSource int32

const (
	// From the foreground process
	TerminalTitleSource_process TerminalTitleSource = 0
	// From SetTitle API
	TerminalTitleSource_api TerminalTitleSource = 1
)

// Enum value maps for TerminalTitleSource.
var (
	TerminalTitleSource_name = map[int32]string{
		0: "process",
		1: "api",
	}
	TerminalTitleSource_value = map[string]int32{
		"process": 0,
		"api":     1,
	}
)

func (x TerminalTitleSource) Enum() *TerminalTitleSource {
	p := new(TerminalTitleSource)
	*p = x
	return p
}

func (x TerminalTitleSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TerminalTitleSource) Descriptor() protoreflect.EnumDescriptor {
	return file_terminal_proto_enumTypes[0].Descriptor()
}

func (TerminalTitleSource) Type() protoreflect.EnumType {
	return &file_terminal_proto_enumTypes[0]
}

func (x TerminalTitleSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TerminalTitleSource.Descriptor instead.
func (TerminalTitleSource) EnumDescriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{0}
}

type TerminalSize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          uint32                 `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	WidthPx       uint32                 `protobuf:"varint,3,opt,name=widthPx,proto3" json:"widthPx,omitempty"`
	HeightPx      uint32                 `protobuf:"varint,4,opt,name=heightPx,proto3" json:"heightPx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalSize) Reset() {
	*x = TerminalSize{}
	mi := &file_terminal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalSize) ProtoMessage() {}

func (x *TerminalSize) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalSize.ProtoReflect.Descriptor instead.
func (*TerminalSize) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{0}
}

func (x *TerminalSize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *TerminalSize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *TerminalSize) GetWidthPx() uint32 {
	if x != nil {
		return x.WidthPx
	}
	return 0
}

func (x *TerminalSize) GetHeightPx() uint32 {
	if x != nil {
		return x.HeightPx
	}
	return 0
}

type OpenTerminalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workdir       string                 `protobuf:"bytes,1,opt,name=workdir,proto3" json:"workdir,omitempty"`
	Env           map[string]string      `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations   map[string]string      `protobuf:"bytes,3,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Shell         string                 `protobuf:"bytes,4,opt,name=shell,proto3" json:"shell,omitempty"`
	ShellArgs     []string               `protobuf:"bytes,5,rep,name=shell_args,json=shellArgs,proto3" json:"shell_args,omitempty"`
	Size          *TerminalSize          `protobuf:"bytes,6,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenTerminalRequest) Reset() {
	*x = OpenTerminalRequest{}
	mi := &file_terminal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenTerminalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenTerminalRequest) ProtoMessage() {}

func (x *OpenTerminalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenTerminalRequest.ProtoReflect.Descriptor instead.
func (*OpenTerminalRequest) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{1}
}

func (x *OpenTerminalRequest) GetWorkdir() string {
	if x != nil {
		return x.Workdir
	}
	return ""
}

func (x *OpenTerminalRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *OpenTerminalRequest) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *OpenTerminalRequest) GetShell() string {
	if x != nil {
		return x.Shell
	}
	return ""
}

func (x *OpenTerminalRequest) GetShellArgs() []string {
	if x != nil {
		return x.ShellArgs
	}
	return nil
}

func (x *OpenTerminalRequest) GetSize() *TerminalSize {
	if x != nil {
		return x.Size
	}
	return nil
}

type OpenTerminalResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Terminal *Terminal              `protobuf:"bytes,1,opt,name=terminal,proto3" json:"terminal,omitempty"`
	// starter_token can be used to change the terminal size if there are
	// multiple listerns, without having to force your way in.
	StarterToken  string `protobuf:"bytes,2,opt,name=starter_token,json=starterToken,proto3" json:"starter_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenTerminalResponse) Reset() {
	*x = OpenTerminalResponse{}
	mi := &file_terminal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenTerminalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenTerminalResponse) ProtoMessage() {}

func (x *OpenTerminalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenTerminalResponse.ProtoReflect.Descriptor instead.
func (*OpenTerminalResponse) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{2}
}

func (x *OpenTerminalResponse) GetTerminal() *Terminal {
	if x != nil {
		return x.Terminal
	}
	return nil
}

func (x *OpenTerminalResponse) GetStarterToken() string {
	if x != nil {
		return x.StarterToken
	}
	return ""
}

type ShutdownTerminalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         string                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	ForceSuccess  bool                   `protobuf:"varint,2,opt,name=force_success,json=forceSuccess,proto3" json:"force_success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownTerminalRequest) Reset() {
	*x = ShutdownTerminalRequest{}
	mi := &file_terminal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownTerminalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownTerminalRequest) ProtoMessage() {}

func (x *ShutdownTerminalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownTerminalRequest.ProtoReflect.Descriptor instead.
func (*ShutdownTerminalRequest) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{3}
}

func (x *ShutdownTerminalRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *ShutdownTerminalRequest) GetForceSuccess() bool {
	if x != nil {
		return x.ForceSuccess
	}
	return false
}

type ShutdownTerminalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownTerminalResponse) Reset() {
	*x = ShutdownTerminalResponse{}
	mi := &file_terminal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownTerminalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownTerminalResponse) ProtoMessage() {}

func (x *ShutdownTerminalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownTerminalResponse.ProtoReflect.Descriptor instead.
func (*ShutdownTerminalResponse) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{4}
}

type Terminal struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Alias          string                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	Command        []string               `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	Title          string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Pid            int64                  `protobuf:"varint,4,opt,name=pid,proto3" json:"pid,omitempty"`
	InitialWorkdir string                 `protobuf:"bytes,5,opt,name=initial_workdir,json=initialWorkdir,proto3" json:"initial_workdir,omitempty"`
	CurrentWorkdir string                 `protobuf:"bytes,6,opt,name=current_workdir,json=currentWorkdir,proto3" json:"current_workdir,omitempty"`
	Annotations    map[string]string      `protobuf:"bytes,7,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TitleSource    TerminalTitleSource    `protobuf:"varint,8,opt,name=title_source,json=titleSource,proto3,enum=supervisor.TerminalTitleSource" json:"title_source,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Terminal) Reset() {
	*x = Terminal{}
	mi := &file_terminal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Terminal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Terminal) ProtoMessage() {}

func (x *Terminal) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Terminal.ProtoReflect.Descriptor instead.
func (*Terminal) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{5}
}

func (x *Terminal) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *Terminal) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *Terminal) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Terminal) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Terminal) GetInitialWorkdir() string {
	if x != nil {
		return x.InitialWorkdir
	}
	return ""
}

func (x *Terminal) GetCurrentWorkdir() string {
	if x != nil {
		return x.CurrentWorkdir
	}
	return ""
}

func (x *Terminal) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *Terminal) GetTitleSource() TerminalTitleSource {
	if x != nil {
		return x.TitleSource
	}
	return TerminalTitleSource_process
}

type GetTerminalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         string                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTerminalRequest) Reset() {
	*x = GetTerminalRequest{}
	mi := &file_terminal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTerminalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTerminalRequest) ProtoMessage() {}

func (x *GetTerminalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTerminalRequest.ProtoReflect.Descriptor instead.
func (*GetTerminalRequest) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{6}
}

func (x *GetTerminalRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type ListTerminalsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTerminalsRequest) Reset() {
	*x = ListTerminalsRequest{}
	mi := &file_terminal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTerminalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTerminalsRequest) ProtoMessage() {}

func (x *ListTerminalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTerminalsRequest.ProtoReflect.Descriptor instead.
func (*ListTerminalsRequest) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{7}
}

type ListTerminalsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Terminals     []*Terminal            `protobuf:"bytes,1,rep,name=terminals,proto3" json:"terminals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTerminalsResponse) Reset() {
	*x = ListTerminalsResponse{}
	mi := &file_terminal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTerminalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTerminalsResponse) ProtoMessage() {}

func (x *ListTerminalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTerminalsResponse.ProtoReflect.Descriptor instead.
func (*ListTerminalsResponse) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{8}
}

func (x *ListTerminalsResponse) GetTerminals() []*Terminal {
	if x != nil {
		return x.Terminals
	}
	return nil
}

type ListenTerminalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         string                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenTerminalRequest) Reset() {
	*x = ListenTerminalRequest{}
	mi := &file_terminal_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenTerminalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenTerminalRequest) ProtoMessage() {}

func (x *ListenTerminalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenTerminalRequest.ProtoReflect.Descriptor instead.
func (*ListenTerminalRequest) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{9}
}

func (x *ListenTerminalRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type ListenTerminalResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Output:
	//
	//	*ListenTerminalResponse_Data
	//	*ListenTerminalResponse_ExitCode
	//	*ListenTerminalResponse_Title
	Output isListenTerminalResponse_Output `protobuf_oneof:"output"`
	// only present if output is title
	TitleSource   TerminalTitleSource `protobuf:"varint,4,opt,name=title_source,json=titleSource,proto3,enum=supervisor.TerminalTitleSource" json:"title_source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenTerminalResponse) Reset() {
	*x = ListenTerminalResponse{}
	mi := &file_terminal_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenTerminalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenTerminalResponse) ProtoMessage() {}

func (x *ListenTerminalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenTerminalResponse.ProtoReflect.Descriptor instead.
func (*ListenTerminalResponse) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{10}
}

func (x *ListenTerminalResponse) GetOutput() isListenTerminalResponse_Output {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ListenTerminalResponse) GetData() []byte {
	if x != nil {
		if x, ok := x.Output.(*ListenTerminalResponse_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *ListenTerminalResponse) GetExitCode() int32 {
	if x != nil {
		if x, ok := x.Output.(*ListenTerminalResponse_ExitCode); ok {
			return x.ExitCode
		}
	}
	return 0
}

func (x *ListenTerminalResponse) GetTitle() string {
	if x != nil {
		if x, ok := x.Output.(*ListenTerminalResponse_Title); ok {
			return x.Title
		}
	}
	return ""
}

func (x *ListenTerminalResponse) GetTitleSource() TerminalTitleSource {
	if x != nil {
		return x.TitleSource
	}
	return TerminalTitleSource_process
}

type isListenTerminalResponse_Output interface {
	isListenTerminalResponse_Output()
}

type ListenTerminalResponse_Data struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type ListenTerminalResponse_ExitCode struct {
	ExitCode int32 `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3,oneof"`
}

type ListenTerminalResponse_Title struct {
	Title string `protobuf:"bytes,3,opt,name=title,proto3,oneof"`
}

func (*ListenTerminalResponse_Data) isListenTerminalResponse_Output() {}

func (*ListenTerminalResponse_ExitCode) isListenTerminalResponse_Output() {}

func (*ListenTerminalResponse_Title) isListenTerminalResponse_Output() {}

type WriteTerminalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         string                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	Stdin         []byte                 `protobuf:"bytes,2,opt,name=stdin,proto3" json:"stdin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteTerminalRequest) Reset() {
	*x = WriteTerminalRequest{}
	mi := &file_terminal_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteTerminalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteTerminalRequest) ProtoMessage() {}

func (x *WriteTerminalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteTerminalRequest.ProtoReflect.Descriptor instead.
func (*WriteTerminalRequest) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{11}
}

func (x *WriteTerminalRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *WriteTerminalRequest) GetStdin() []byte {
	if x != nil {
		return x.Stdin
	}
	return nil
}

type WriteTerminalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BytesWritten  uint32                 `protobuf:"varint,1,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteTerminalResponse) Reset() {
	*x = WriteTerminalResponse{}
	mi := &file_terminal_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteTerminalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteTerminalResponse) ProtoMessage() {}

func (x *WriteTerminalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteTerminalResponse.ProtoReflect.Descriptor instead.
func (*WriteTerminalResponse) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{12}
}

func (x *WriteTerminalResponse) GetBytesWritten() uint32 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

type SetTerminalSizeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Alias string                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	// token is the starter_token that Open() returned.
	// Without token it's possible that the request is ignored.
	// If you want to force your size, independently of all other listener, use force.
	//
	// Types that are valid to be assigned to Priority:
	//
	//	*SetTerminalSizeRequest_Token
	//	*SetTerminalSizeRequest_Force
	Priority      isSetTerminalSizeRequest_Priority `protobuf_oneof:"priority"`
	Size          *TerminalSize                     `protobuf:"bytes,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTerminalSizeRequest) Reset() {
	*x = SetTerminalSizeRequest{}
	mi := &file_terminal_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTerminalSizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTerminalSizeRequest) ProtoMessage() {}

func (x *SetTerminalSizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTerminalSizeRequest.ProtoReflect.Descriptor instead.
func (*SetTerminalSizeRequest) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{13}
}

func (x *SetTerminalSizeRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *SetTerminalSizeRequest) GetPriority() isSetTerminalSizeRequest_Priority {
	if x != nil {
		return x.Priority
	}
	return nil
}

func (x *SetTerminalSizeRequest) GetToken() string {
	if x != nil {
		if x, ok := x.Priority.(*SetTerminalSizeRequest_Token); ok {
			return x.Token
		}
	}
	return ""
}

func (x *SetTerminalSizeRequest) GetForce() bool {
	if x != nil {
		if x, ok := x.Priority.(*SetTerminalSizeRequest_Force); ok {
			return x.Force
		}
	}
	return false
}

func (x *SetTerminalSizeRequest) GetSize() *TerminalSize {
	if x != nil {
		return x.Size
	}
	return nil
}

type isSetTerminalSizeRequest_Priority interface {
	isSetTerminalSizeRequest_Priority()
}

type SetTerminalSizeRequest_Token struct {
	Token string `protobuf:"bytes,2,opt,name=token,proto3,oneof"`
}

type SetTerminalSizeRequest_Force struct {
	Force bool `protobuf:"varint,3,opt,name=force,proto3,oneof"`
}

func (*SetTerminalSizeRequest_Token) isSetTerminalSizeRequest_Priority() {}

func (*SetTerminalSizeRequest_Force) isSetTerminalSizeRequest_Priority() {}

type SetTerminalSizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTerminalSizeResponse) Reset() {
	*x = SetTerminalSizeResponse{}
	mi := &file_terminal_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTerminalSizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTerminalSizeResponse) ProtoMessage() {}

func (x *SetTerminalSizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTerminalSizeResponse.ProtoReflect.Descriptor instead.
func (*SetTerminalSizeResponse) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{14}
}

type SetTerminalTitleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Alias string                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	// omitting title will reset to process title
	Title         string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTerminalTitleRequest) Reset() {
	*x = SetTerminalTitleRequest{}
	mi := &file_terminal_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTerminalTitleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTerminalTitleRequest) ProtoMessage() {}

func (x *SetTerminalTitleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTerminalTitleRequest.ProtoReflect.Descriptor instead.
func (*SetTerminalTitleRequest) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{15}
}

func (x *SetTerminalTitleRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *SetTerminalTitleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type SetTerminalTitleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTerminalTitleResponse) Reset() {
	*x = SetTerminalTitleResponse{}
	mi := &file_terminal_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTerminalTitleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTerminalTitleResponse) ProtoMessage() {}

func (x *SetTerminalTitleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTerminalTitleResponse.ProtoReflect.Descriptor instead.
func (*SetTerminalTitleResponse) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{16}
}

type UpdateTerminalAnnotationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Alias string                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	// annotations to create or update
	Changed map[string]string `protobuf:"bytes,2,rep,name=changed,proto3" json:"changed,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// annotations to remove
	Deleted       []string `protobuf:"bytes,3,rep,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTerminalAnnotationsRequest) Reset() {
	*x = UpdateTerminalAnnotationsRequest{}
	mi := &file_terminal_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTerminalAnnotationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTerminalAnnotationsRequest) ProtoMessage() {}

func (x *UpdateTerminalAnnotationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTerminalAnnotationsRequest.ProtoReflect.Descriptor instead.
func (*UpdateTerminalAnnotationsRequest) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateTerminalAnnotationsRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *UpdateTerminalAnnotationsRequest) GetChanged() map[string]string {
	if x != nil {
		return x.Changed
	}
	return nil
}

func (x *UpdateTerminalAnnotationsRequest) GetDeleted() []string {
	if x != nil {
		return x.Deleted
	}
	return nil
}

type UpdateTerminalAnnotationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTerminalAnnotationsResponse) Reset() {
	*x = UpdateTerminalAnnotationsResponse{}
	mi := &file_terminal_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTerminalAnnotationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTerminalAnnotationsResponse) ProtoMessage() {}

func (x *UpdateTerminalAnnotationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTerminalAnnotationsResponse.ProtoReflect.Descriptor instead.
func (*UpdateTerminalAnnotationsResponse) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{18}
}

var File_terminal_proto protoreflect.FileDescriptor

const file_terminal_proto_rawDesc = "" +
	"\n" +
	"\x0eterminal.proto\x12\n" +
	"supervisor\"l\n" +
	"\fTerminalSize\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\x12\x18\n" +
	"\awidthPx\x18\x03 \x01(\rR\awidthPx\x12\x1a\n" +
	"\bheightPx\x18\x04 \x01(\rR\bheightPx\"\x9a\x03\n" +
	"\x13OpenTerminalRequest\x12\x18\n" +
	"\aworkdir\x18\x01 \x01(\tR\aworkdir\x12:\n" +
	"\x03env\x18\x02 \x03(\v2(.supervisor.OpenTerminalRequest.EnvEntryR\x03env\x12R\n" +
	"\vannotations\x18\x03 \x03(\v20.supervisor.OpenTerminalRequest.AnnotationsEntryR\vannotations\x12\x14\n" +
	"\x05shell\x18\x04 \x01(\tR\x05shell\x12\x1d\n" +
	"\n" +
	"shell_args\x18\x05 \x03(\tR\tshellArgs\x12,\n" +
	"\x04size\x18\x06 \x01(\v2\x18.supervisor.TerminalSizeR\x04size\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"m\n" +
	"\x14OpenTerminalResponse\x120\n" +
	"\bterminal\x18\x01 \x01(\v2\x14.supervisor.TerminalR\bterminal\x12#\n" +
	"\rstarter_token\x18\x02 \x01(\tR\fstarterToken\"T\n" +
	"\x17ShutdownTerminalRequest\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\x12#\n" +
	"\rforce_success\x18\x02 \x01(\bR\fforceSuccess\"\x1a\n" +
	"\x18ShutdownTerminalResponse\"\x81\x03\n" +
	"\bTerminal\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x10\n" +
	"\x03pid\x18\x04 \x01(\x03R\x03pid\x12'\n" +
	"\x0finitial_workdir\x18\x05 \x01(\tR\x0einitialWorkdir\x12'\n" +
	"\x0fcurrent_workdir\x18\x06 \x01(\tR\x0ecurrentWorkdir\x12G\n" +
	"\vannotations\x18\a \x03(\v2%.supervisor.Terminal.AnnotationsEntryR\vannotations\x12B\n" +
	"\ftitle_source\x18\b \x01(\x0e2\x1f.supervisor.TerminalTitleSourceR\vtitleSource\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"*\n" +
	"\x12GetTerminalRequest\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\"\x16\n" +
	"\x14ListTerminalsRequest\"K\n" +
	"\x15ListTerminalsResponse\x122\n" +
	"\tterminals\x18\x01 \x03(\v2\x14.supervisor.TerminalR\tterminals\"-\n" +
	"\x15ListenTerminalRequest\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\"\xb3\x01\n" +
	"\x16ListenTerminalResponse\x12\x14\n" +
	"\x04data\x18\x01 \x01(\fH\x00R\x04data\x12\x1d\n" +
	"\texit_code\x18\x02 \x01(\x05H\x00R\bexitCode\x12\x16\n" +
	"\x05title\x18\x03 \x01(\tH\x00R\x05title\x12B\n" +
	"\ftitle_source\x18\x04 \x01(\x0e2\x1f.supervisor.TerminalTitleSourceR\vtitleSourceB\b\n" +
	"\x06output\"B\n" +
	"\x14WriteTerminalRequest\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\x12\x14\n" +
	"\x05stdin\x18\x02 \x01(\fR\x05stdin\"<\n" +
	"\x15WriteTerminalResponse\x12#\n" +
	"\rbytes_written\x18\x01 \x01(\rR\fbytesWritten\"\x98\x01\n" +
	"\x16SetTerminalSizeRequest\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\x12\x16\n" +
	"\x05token\x18\x02 \x01(\tH\x00R\x05token\x12\x16\n" +
	"\x05force\x18\x03 \x01(\bH\x00R\x05force\x12,\n" +
	"\x04size\x18\x04 \x01(\v2\x18.supervisor.TerminalSizeR\x04sizeB\n" +
	"\n" +
	"\bpriority\"\x19\n" +
	"\x17SetTerminalSizeResponse\"E\n" +
	"\x17SetTerminalTitleRequest\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"\x1a\n" +
	"\x18SetTerminalTitleResponse\"\xe3\x01\n" +
	" UpdateTerminalAnnotationsRequest\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\x12S\n" +
	"\achanged\x18\x02 \x03(\v29.supervisor.UpdateTerminalAnnotationsRequest.ChangedEntryR\achanged\x12\x18\n" +
	"\adeleted\x18\x03 \x03(\tR\adeleted\x1a:\n" +
	"\fChangedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"#\n" +
	"!UpdateTerminalAnnotationsResponse*+\n" +
	"\x13TerminalTitleSource\x12\v\n" +
	"\aprocess\x10\x00\x12\a\n" +
	"\x03api\x10\x012\x8d\x06\n" +
	"\x0fTerminalService\x12K\n" +
	"\x04Open\x12\x1f.supervisor.OpenTerminalRequest\x1a .supervisor.OpenTerminalResponse\"\x00\x12W\n" +
	"\bShutdown\x12#.supervisor.ShutdownTerminalRequest\x1a$.supervisor.ShutdownTerminalResponse\"\x00\x12=\n" +
	"\x03Get\x12\x1e.supervisor.GetTerminalRequest\x1a\x14.supervisor.Terminal\"\x00\x12M\n" +
	"\x04List\x12 .supervisor.ListTerminalsRequest\x1a!.supervisor.ListTerminalsResponse\"\x00\x12S\n" +
	"\x06Listen\x12!.supervisor.ListenTerminalRequest\x1a\".supervisor.ListenTerminalResponse\"\x000\x01\x12N\n" +
	"\x05Write\x12 .supervisor.WriteTerminalRequest\x1a!.supervisor.WriteTerminalResponse\"\x00\x12T\n" +
	"\aSetSize\x12\".supervisor.SetTerminalSizeRequest\x1a#.supervisor.SetTerminalSizeResponse\"\x00\x12W\n" +
	"\bSetTitle\x12#.supervisor.SetTerminalTitleRequest\x1a$.supervisor.SetTerminalTitleResponse\"\x00\x12r\n" +
	"\x11UpdateAnnotations\x12,.supervisor.UpdateTerminalAnnotationsRequest\x1a-.supervisor.UpdateTerminalAnnotationsResponse\"\x00B\x10Z\x0esupervisor/apib\x06proto3"

var (
	file_terminal_proto_rawDescOnce sync.Once
	file_terminal_proto_rawDescData []byte
)

func file_terminal_proto_rawDescGZIP() []byte {
	file_terminal_proto_rawDescOnce.Do(func() {
		file_terminal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_terminal_proto_rawDesc), len(file_terminal_proto_rawDesc)))
	})
	return file_terminal_proto_rawDescData
}

var file_terminal_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_terminal_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_terminal_proto_goTypes = []any{
	(TerminalTitleSource)(0),                  // 0: supervisor.TerminalTitleSource
	(*TerminalSize)(nil),                      // 1: supervisor.TerminalSize
	(*OpenTerminalRequest)(nil),               // 2: supervisor.OpenTerminalRequest
	(*OpenTerminalResponse)(nil),              // 3: supervisor.OpenTerminalResponse
	(*ShutdownTerminalRequest)(nil),           // 4: supervisor.ShutdownTerminalRequest
	(*ShutdownTerminalResponse)(nil),          // 5: supervisor.ShutdownTerminalResponse
	(*Terminal)(nil),                          // 6: supervisor.Terminal
	(*GetTerminalRequest)(nil),                // 7: supervisor.GetTerminalRequest
	(*ListTerminalsRequest)(nil),              // 8: supervisor.ListTerminalsRequest
	(*ListTerminalsResponse)(nil),             // 9: supervisor.ListTerminalsResponse
	(*ListenTerminalRequest)(nil),             // 10: supervisor.ListenTerminalRequest
	(*ListenTerminalResponse)(nil),            // 11: supervisor.ListenTerminalResponse
	(*WriteTerminalRequest)(nil),              // 12: supervisor.WriteTerminalRequest
	(*WriteTerminalResponse)(nil),             // 13: supervisor.WriteTerminalResponse
	(*SetTerminalSizeRequest)(nil),            // 14: supervisor.SetTerminalSizeRequest
	(*SetTerminalSizeResponse)(nil),           // 15: supervisor.SetTerminalSizeResponse
	(*SetTerminalTitleRequest)(nil),           // 16: supervisor.SetTerminalTitleRequest
	(*SetTerminalTitleResponse)(nil),          // 17: supervisor.SetTerminalTitleResponse
	(*UpdateTerminalAnnotationsRequest)(nil),  // 18: supervisor.UpdateTerminalAnnotationsRequest
	(*UpdateTerminalAnnotationsResponse)(nil), // 19: supervisor.UpdateTerminalAnnotationsResponse
	nil, // 20: supervisor.OpenTerminalRequest.EnvEntry
	nil, // 21: supervisor.OpenTerminalRequest.AnnotationsEntry
	nil, // 22: supervisor.Terminal.AnnotationsEntry
	nil, // 23: supervisor.UpdateTerminalAnnotationsRequest.ChangedEntry
}
var file_terminal_proto_depIdxs = []int32{
	20, // 0: supervisor.OpenTerminalRequest.env:type_name -> supervisor.OpenTerminalRequest.EnvEntry
	21, // 1: supervisor.OpenTerminalRequest.annotations:type_name -> supervisor.OpenTerminalRequest.AnnotationsEntry
	1,  // 2: supervisor.OpenTerminalRequest.size:type_name -> supervisor.TerminalSize
	6,  // 3: supervisor.OpenTerminalResponse.terminal:type_name -> supervisor.Terminal
	22, // 4: supervisor.Terminal.annotations:type_name -> supervisor.Terminal.AnnotationsEntry
	0,  // 5: supervisor.Terminal.title_source:type_name -> supervisor.TerminalTitleSource
	6,  // 6: supervisor.ListTerminalsResponse.terminals:type_name -> supervisor.Terminal
	0,  // 7: supervisor.ListenTerminalResponse.title_source:type_name -> supervisor.TerminalTitleSource
	1,  // 8: supervisor.SetTerminalSizeRequest.size:type_name -> supervisor.TerminalSize
	23, // 9: supervisor.UpdateTerminalAnnotationsRequest.changed:type_name -> supervisor.UpdateTerminalAnnotationsRequest.ChangedEntry
	2,  // 10: supervisor.TerminalService.Open:input_type -> supervisor.OpenTerminalRequest
	4,  // 11: supervisor.TerminalService.Shutdown:input_type -> supervisor.ShutdownTerminalRequest
	7,  // 12: supervisor.TerminalService.Get:input_type -> supervisor.GetTerminalRequest
	8,  // 13: supervisor.TerminalService.List:input_type -> supervisor.ListTerminalsRequest
	10, // 14: supervisor.TerminalService.Listen:input_type -> supervisor.ListenTerminalRequest
	12, // 15: supervisor.TerminalService.Write:input_type -> supervisor.WriteTerminalRequest
	14, // 16: supervisor.TerminalService.SetSize:input_type -> supervisor.SetTerminalSizeRequest
	16, // 17: supervisor.TerminalService.SetTitle:input_type -> supervisor.SetTerminalTitleRequest
	18, // 18: supervisor.TerminalService.UpdateAnnotations:input_type -> supervisor.UpdateTerminalAnnotationsRequest
	3,  // 19: supervisor.TerminalService.Open:output_type -> supervisor.OpenTerminalResponse
	5,  // 20: supervisor.TerminalService.Shutdown:output_type -> supervisor.ShutdownTerminalResponse
	6,  // 21: supervisor.TerminalService.Get:output_type -> supervisor.Terminal
	9,  // 22: supervisor.TerminalService.List:output_type -> supervisor.ListTerminalsResponse
	11, // 23: supervisor.TerminalService.Listen:output_type -> supervisor.ListenTerminalResponse
	13, // 24: supervisor.TerminalService.Write:output_type -> supervisor.WriteTerminalResponse
	15, // 25: supervisor.TerminalService.SetSize:output_type -> supervisor.SetTerminalSizeResponse
	17, // 26: supervisor.TerminalService.SetTitle:output_type -> supervisor.SetTerminalTitleResponse
	19, // 27: supervisor.TerminalService.UpdateAnnotations:output_type -> supervisor.UpdateTerminalAnnotationsResponse
	19, // [19:28] is the sub-list for method output_type
	10, // [10:19] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_terminal_proto_init() }
func file_terminal_proto_init() {
	if File_terminal_proto != nil {
		return
	}
	file_terminal_proto_msgTypes[10].OneofWrappers = []any{
		(*ListenTerminalResponse_Data)(nil),
		(*ListenTerminalResponse_ExitCode)(nil),
		(*ListenTerminalResponse_Title)(nil),
	}
	file_terminal_proto_msgTypes[13].OneofWrappers = []any{
		(*SetTerminalSizeRequest_Token)(nil),
		(*SetTerminalSizeRequest_Force)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_terminal_proto_rawDesc), len(file_terminal_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_terminal_proto_goTypes,
		DependencyIndexes: file_terminal_proto_depIdxs,
		EnumInfos:         file_terminal_proto_enumTypes,
		MessageInfos:      file_terminal_proto_msgTypes,
	}.Build()
	File_terminal_proto = out.File
	file_terminal_proto_goTypes = nil
	file_terminal_proto_depIdxs = nil
}
